const FACTS={
'Washington':'Mount St. Helens and Mount Rainier are volcanoes in the Cascade Range.',
'Oregon':'Crater Lake fills a volcanic basin called a caldera.',
'California':'The Golden Gate Bridge crosses the entrance to San Francisco Bay.',
'Idaho':'The Snake River runs through Hells Canyon along the Idaho–Oregon border.',
'Nevada':'Las Vegas is in the Mojave Desert. Its bright lights do not make it the state capital!',
'Utah':'Bryce Canyon is famous for tall rock spires called hoodoos.',
'Arizona':'The Colorado River flows through the Grand Canyon.',
'Montana':'Glacier National Park has mountain lakes and valleys carved by ice.',
'Wyoming':'Old Faithful is a geyser in Yellowstone National Park.',
'Colorado':'The Rocky Mountains cross Colorado. Denver is nicknamed the Mile High City.',
'New Mexico':'White Sands has dunes made of white gypsum sand.',
'North Dakota':'Theodore Roosevelt National Park protects colorful badlands and grasslands.',
'South Dakota':'Mount Rushmore has four presidents’ faces carved into a mountainside.',
'Nebraska':'The Platte River is a resting place for migrating sandhill cranes.',
'Kansas':'Kansas is known as the Sunflower State.',
'Oklahoma':'The state’s name comes from Choctaw words referring to red people.',
'Texas':'The Alamo stands in San Antonio, but the state capital is Austin.',
'Minnesota':'The Mississippi River begins at Lake Itasca.',
'Iowa':'Iowa lies between the Missouri River on the west and the Mississippi on the east.',
'Missouri':'The Gateway Arch rises above the Mississippi River in St. Louis.',
'Arkansas':'Hot Springs National Park protects naturally heated spring water.',
'Louisiana':'The Mississippi River reaches the Gulf through Louisiana’s delta.',
'Michigan':'Michigan has two peninsulas connected by the Mackinac Bridge.',
'Wisconsin':'Wisconsin is famous for dairy farming and cheese.',
'Illinois':'Chicago stands beside Lake Michigan, but Springfield is the capital.',
'Kentucky':'Mammoth Cave has an enormous network of underground passages.',
'Ohio':'The Wright brothers developed their airplane ideas in Dayton.',
'Indiana':'The Indianapolis 500 is a famous automobile race.',
'Tennessee':'The Great Smoky Mountains stretch along the Tennessee–North Carolina border.',
'Mississippi':'The state shares its name with the great river along its western side.',
'Alabama':'Huntsville has a long history of building rockets for space exploration.',
'Florida':'The Everglades is a vast wetland with slowly moving water.',
'Georgia':'Savannah is known for its historic squares and live oak trees.',
'South Carolina':'Columbia lies inland, while Charleston is on the coast.',
'North Carolina':'The Wright brothers made their first powered flights near Kitty Hawk.',
'Virginia':'Colonial Williamsburg recreates life in a historic colonial capital.',
'West Virginia':'The New River Gorge is crossed by a huge steel arch bridge.',
'Maryland':'The United States Naval Academy is in Annapolis.',
'Delaware':'Delaware was the first state to ratify the U.S. Constitution.',
'Pennsylvania':'The Declaration of Independence was adopted in Philadelphia.',
'New Jersey':'New Jersey is nicknamed the Garden State.',
'New York':'The Erie Canal connects the Hudson River with Lake Erie.',
'Connecticut':'The United States Coast Guard Academy is in New London.',
'Rhode Island':'Rhode Island is the smallest U.S. state by area.',
'Massachusetts':'Cape Cod curves into the Atlantic like a bent arm.',
'Vermont':'Maple trees provide sap that can be boiled into maple syrup.',
'New Hampshire':'Mount Washington is known for powerful winds and rapidly changing weather.',
'Maine':'Maine’s rocky Atlantic coast has many lighthouses.',
'Alaska':'Alaska is separated from the other mainland states by Canada.',
'Hawaii':'Hawaii is a chain of volcanic islands in the Pacific Ocean.',
'Canada':'Canada and the United States share the Great Lakes.',
'United States':'Washington, D.C., is a federal district; it is not in Washington state.',
'Mexico':'Mexico City stands in a high valley surrounded by mountains.',
'Belize':'Belize has a barrier reef along its Caribbean coast.',
'Guatemala':'Ancient Maya temples rise above the forest at Tikal.',
'El Salvador':'El Salvador has a Pacific coast but no Caribbean coast.',
'Honduras':'The Maya city of Copán is known for carved stone monuments.',
'Nicaragua':'Lake Nicaragua contains islands formed by volcanoes.',
'Costa Rica':'Costa Rica has coastlines on both the Pacific Ocean and the Caribbean Sea.',
'Panama':'The Panama Canal provides a shipping route between the Atlantic and Pacific.',
'Bahamas':'The Bahamas is an archipelago—a group of islands—in the Atlantic Ocean.',
'Cuba':'Cuba is the largest island in the Caribbean.',
'Jamaica':'The Blue Mountains rise in the eastern part of Jamaica.',
'Haiti':'Haiti and the Dominican Republic share the island of Hispaniola.',
'Dominican Republic':'The Dominican Republic occupies the eastern part of Hispaniola.',
'Puerto Rico':'Puerto Rico is a U.S. territory. El Yunque is a tropical rainforest there.',
'Saint Kitts and Nevis':'This country’s name names its two main islands.',
'Antigua and Barbuda':'Antigua and Barbuda are two islands in the same country.',
'Dominica':'Dominica is a different country from the Dominican Republic.',
'Saint Lucia':'Two steep volcanic peaks called the Pitons rise near the coast.',
'Barbados':'Barbados lies east of the main arc of the Lesser Antilles.',
'Saint Vincent and the Grenadines':'This country includes Saint Vincent and a chain of smaller islands.',
'Grenada':'Grenada is known for spices, including nutmeg.',
'Trinidad and Tobago':'Steelpan music developed in Trinidad and Tobago.',
'Colombia':'Colombia has coastlines on both the Pacific and the Caribbean.',
'Ecuador':'Ecuador takes its name from the equator, which crosses the country.',
'Peru':'Machu Picchu is an Inca site high in the Andes.',
'Chile':'Chile forms a long, narrow strip between the Andes and the Pacific.',
'Bolivia':'Lake Titicaca lies high in the Andes on the border with Peru.',
'Paraguay':'Paraguay is landlocked: it has no ocean coastline.',
'Argentina':'The grassy plains called the Pampas cover part of Argentina.',
'Uruguay':'Uruguay lies between Brazil and Argentina on the Atlantic side of South America.',
'Venezuela':'Angel Falls plunges from a flat-topped mountain in Venezuela.',
'Guyana':'Guyana is on South America’s northern coast, beside the Atlantic.',
'Suriname':'Suriname lies between Guyana and French Guiana.',
'French Guiana':'French Guiana is part of France, even though it is in South America.',
'Brazil':'Portuguese is spoken in Brazil; many neighboring countries use Spanish.',
'Iceland':'Iceland has both glaciers and active volcanoes.',
'Ireland':'Ireland shares its island with Northern Ireland, which is part of the United Kingdom.',
'United Kingdom':'The United Kingdom includes England, Scotland, Wales, and Northern Ireland.',
'Netherlands':'Dikes help keep water away from low-lying land.',
'Belgium':'Belgium is known for chocolate and waffles.',
'Luxembourg':'Luxembourg is a small landlocked country between Belgium, France, and Germany.',
'France':'The Eiffel Tower stands beside the River Seine in Paris.',
'Andorra':'Andorra lies in the Pyrenees mountains between France and Spain.',
'Spain':'Spain and Portugal share the Iberian Peninsula.',
'Portugal':'Portugal faces the Atlantic Ocean on the western edge of the Iberian Peninsula.',
'Norway':'Deep sea inlets called fjords cut into Norway’s coast.',
'Sweden':'Sweden occupies the eastern side of the Scandinavian Peninsula.',
'Finland':'Finland has many lakes and forests.',
'Estonia':'Estonia is the northernmost of the three Baltic states.',
'Latvia':'Latvia is the middle of the three Baltic states.',
'Lithuania':'Lithuania is the southernmost of the three Baltic states.',
'Denmark':'Denmark includes a peninsula and many islands.',
'Germany':'The Rhine is one of Germany’s major rivers.',
'Switzerland':'The Alps cover much of southern Switzerland.',
'Liechtenstein':'Liechtenstein is tucked between Switzerland and Austria.',
'San Marino':'San Marino is surrounded by Italy.',
'Italy':'Italy’s peninsula is famously shaped like a boot.',
'Vatican City':'Vatican City is a small independent state inside Rome.',
'Malta':'Malta is an island country in the Mediterranean, south of Sicily.',
'Czechia':'Prague’s Charles Bridge crosses the Vltava River.',
'Austria':'The Danube River flows through Vienna.',
'Slovenia':'Slovenia has both Alpine mountains and a short Adriatic coastline.',
'Croatia':'Croatia has a long Adriatic coast with many islands.',
'Bosnia and Herzegovina':'The country has a short stretch of Adriatic coastline at Neum.',
'Montenegro':'Montenegro has mountains close to its Adriatic coast.',
'Albania':'Albania faces the Adriatic and Ionian seas.',
'Poland':'The Vistula River flows through Warsaw toward the Baltic Sea.',
'Slovakia':'The Tatra Mountains lie along the border with Poland.',
'Hungary':'Budapest straddles the Danube River.',
'Serbia':'The Danube and Sava rivers meet at Belgrade.',
'Kosovo':'Kosovo is landlocked in the Balkan region of Europe.',
'North Macedonia':'Lake Ohrid lies on the border with Albania.',
'Greece':'Greece includes a mainland peninsula and many islands.',
'Belarus':'Belarus has no coastline; it is surrounded by other countries.',
'Ukraine':'The Dnipro River flows through Kyiv toward the Black Sea.',
'Moldova':'Moldova lies between Romania and Ukraine.',
'Romania':'The Carpathian Mountains curve through Romania.',
'Bulgaria':'Bulgaria has a coast on the Black Sea.',
'Russia':'Russia stretches across both Europe and Asia.',
'Georgia-country':'The Caucasus Mountains rise along Georgia’s northern side.',
'Azerbaijan':'Azerbaijan borders the Caspian Sea.',
'Armenia':'Armenia is a mountainous, landlocked country in the South Caucasus.'
};

// Spring discoveries from the classroom slides.
Object.assign(FACTS,{"Turkey": "Your class explores Byzantium, Constantinople, Istanbul. What catches your attention about this place?", "Cyprus": "Your class explores The Mosaics of Paphos. What catches your attention about this place?", "Lebanon": "Your class explores Stone of the pregnant woman. What catches your attention about this place?", "Israel": "Your class explores the Sea of Galilee. What catches your attention about this place?", "Syria": "Your class explores Krak des Chevaliers. What catches your attention about this place?", "Jordan": "Your class explores Petra. What catches your attention about this place?", "Iran": "Your class explores Shah Cheragh. What catches your attention about this place?", "Iraq": "Your class explores Babylon. What catches your attention about this place?", "Kuwait": "Your class explores House of Mirrors. What catches your attention about this place?", "Saudi Arabia": "Your class explores Mecca. What catches your attention about this place?", "Bahrain": "Your class explores Tree of Life. What catches your attention about this place?", "Qatar": "Your class explores Al Wukair Scrapyard. What catches your attention about this place?", "United Arab Emirates": "Your class explores Ferrari World. What catches your attention about this place?", "Oman": "Your class explores Chandelier at the Sultan Qaboos Grand Mosque. What catches your attention about this place?", "Yemen": "Your class explores Socotra Island. What catches your attention about this place?", "Kazakhstan": "Your class explores Aral Sea. What catches your attention about this place?", "Uzbekistan": "Your class explores Moynaq. What catches your attention about this place?", "Turkmenistan": "Your class explores Türkmenbaşy Ruhy Mosque. What catches your attention about this place?", "Afghanistan": "Your class explores Minaret of Jam. What catches your attention about this place?", "Pakistan": "Your class explores Attabad Lake. What catches your attention about this place?", "Kyrgyzstan": "Your class explores Tash Rabat on the Silk Road. What catches your attention about this place?", "Tajikistan": "Your class explores Sarez Lake. What catches your attention about this place?", "Mongolia": "Your class explores Genghis Khan Statue Complex. What catches your attention about this place?", "China": "Your class explores The Forbidden City. What catches your attention about this place?", "India": "Your class explores Taj Mahal. What catches your attention about this place?", "Sri Lanka": "Your class explores Sigiriya. What catches your attention about this place?", "Maldives": "Your class explores Ithaa Undersea Restaurant. What catches your attention about this place?", "Myanmar": "Your class explores the Kakku Pagodas. What catches your attention about this place?", "Thailand": "Your class explores Historic Siam. What catches your attention about this place?", "Malaysia": "Your class explores the Pinnacles of Gunung Mulu. What catches your attention about this place?", "Singapore": "Your class explores Gardens by the Bay. What catches your attention about this place?", "Laos": "Your class explores Kuang Si Waterfalls. What catches your attention about this place?", "Cambodia": "Your class explores Ta Prohm. What catches your attention about this place?", "Vietnam": "Your class explores Golden Bridge. What catches your attention about this place?", "Nepal": "Your class explores Mt Everest. What catches your attention about this place?", "Bhutan": "Your class explores Paro Taktsang: The Tiger's Nest Monastery. What catches your attention about this place?", "Bangladesh": "Your class explores Dahala Khagrabari. What catches your attention about this place?", "North Korea": "Your class explores the border between North and South Korea. What catches your attention about this place?", "South Korea": "Your class explores Changdeokgung. What catches your attention about this place?", "Japan": "Your class explores Mt. Fuji. What catches your attention about this place?", "Taiwan": "Your class explores Tuned Mass Damper of Taipei 101. What catches your attention about this place?", "Philippines": "Your class explores Hinatuan Enchanted River. What catches your attention about this place?", "Brunei": "Your class explores Istana Nurul Iman. What catches your attention about this place?", "Timor-Leste": "Your class explores the Venilale Tunnels. What catches your attention about this place?", "Indonesia": "Your class explores Tanah Lot. What catches your attention about this place?", "Palau": "Your class explores Jelly-fish Lake. What catches your attention about this place?", "Papua New Guinea": "Your class explores Many Languages. What catches your attention about this place?", "Australia": "Your class explores its Aboriginal cultures. What catches your attention about this place?", "New Zealand": "Your class explores Lord of the Rings. What catches your attention about this place?", "Micronesia": "Your class explores Nan Madol Ruins. What catches your attention about this place?", "Nauru": "Your class explores its island landscape. What catches your attention about this place?", "Solomon Islands": "Your class explores The World Discoverer. What catches your attention about this place?", "Vanuatu": "Your class explores Pentecost Island Land Dive. What catches your attention about this place?", "Marshall Islands": "Your class explores Bikini Atoll. What catches your attention about this place?", "Kiribati": "Your class explores Nikumaroro Island. What catches your attention about this place?", "Tuvalu": "Your class explores its Pacific atolls. What catches your attention about this place?", "Fiji": "Your class explores its island landscapes. What catches your attention about this place?", "Samoa": "Your class explores To Sua Ocean Trench. What catches your attention about this place?", "Tonga": "Your class explores its island landscapes. What catches your attention about this place?", "Morocco": "Your class explores Ouarzazate Solar Power Station. What catches your attention about this place?", "Algeria": "Your class explores the Martyrs’ Memorial. What catches your attention about this place?", "Tunisia": "Your class explores its filming locations. What catches your attention about this place?", "Libya": "Your class explores Arch of Marcus Aurelius. What catches your attention about this place?", "Egypt": "Your class explores the Suez Canal. What catches your attention about this place?", "Mauritania": "Your class explores Richat Structure. What catches your attention about this place?", "Mali": "Your class explores Great Mud Mosque of Djenne. What catches your attention about this place?", "Burkina Faso": "Your class explores Cour Royale de Tiébélé. What catches your attention about this place?", "Niger": "Your class explores Last Tree of Ténéré. What catches your attention about this place?", "Chad": "Your class explores Tibesti Mountains. What catches your attention about this place?", "Sudan": "Your class explores Meroe Pyramids. What catches your attention about this place?", "Western Sahara": "Your class explores its desert landscape. What catches your attention about this place?", "Cabo Verde": "Your class explores the Viana Desert. What catches your attention about this place?", "Senegal": "Your class explores The Great Green Wall of Africa. What catches your attention about this place?", "The Gambia": "Your class explores Kachikally Crocodile Pool. What catches your attention about this place?", "Guinea-Bissau": "Your class explores its people and landscapes. What catches your attention about this place?", "Guinea": "Your class explores its rainy landscapes. What catches your attention about this place?", "Sierra Leone": "Your class explores Bunce Island. What catches your attention about this place?", "Liberia": "Your class explores Bomi Blue Lake. What catches your attention about this place?", "Côte d'Ivoire": "Your class explores the Basilica of Our Lady of Peace in Yamoussoukro. What catches your attention about this place?", "Ghana": "Your class explores Kakum Canopy Walk. What catches your attention about this place?", "Togo": "Your class explores Nok Caves. What catches your attention about this place?", "Benin": "Your class explores Ganvie Lake Village. What catches your attention about this place?", "Nigeria": "Your class explores Abuja Airplane House. What catches your attention about this place?", "Cameroon": "Your class explores Mt. Cameroon. What catches your attention about this place?", "Equatorial Guinea": "Your class explores its mainland and island regions. What catches your attention about this place?", "São Tomé and Príncipe": "Your class explores the islands of São Tomé and Príncipe. What catches your attention about this place?", "Gabon": "Your class explores Libreville. What catches your attention about this place?", "Republic of the Congo": "Your class explores Nabemba Tower. What catches your attention about this place?", "Central African Republic": "Your class explores Boali Falls. What catches your attention about this place?", "Democratic Republic of the Congo": "Your class explores Nyiragongo Volcano. What catches your attention about this place?", "Angola": "Your class explores Cemitério de Navios (The Ship Cemetery). What catches your attention about this place?", "Zambia": "Your class explores Devil's Swimming Pool. What catches your attention about this place?", "Eritrea": "Your class explores its people and landscapes. What catches your attention about this place?", "Djibouti": "Your class explores its people and landscapes. What catches your attention about this place?", "Ethiopia": "Your class explores its highland landscapes. What catches your attention about this place?", "Somalia": "Your class explores its people and landscapes. What catches your attention about this place?", "Kenya": "Your class explores Giraffe Manor. What catches your attention about this place?", "Uganda": "Your class explores Murchison Falls. What catches your attention about this place?", "Rwanda": "Your class explores its people and landscapes. What catches your attention about this place?", "Burundi": "Your class explores Kagera Falls. What catches your attention about this place?", "Tanzania": "Your class explores Zanzibar Tanganyika. What catches your attention about this place?", "Comoros": "Your class explores “Perfumed Islands”. What catches your attention about this place?", "Seychelles": "Your class explores Aldabra Atoll. What catches your attention about this place?", "Namibia": "Your class explores Fairy Circles of Southern Africa. What catches your attention about this place?", "Botswana": "Your class explores Khoisan languages. What catches your attention about this place?", "Zimbabwe": "Your class explores The Great Zimbabwe The Valley Complex. What catches your attention about this place?", "Mozambique": "Your class explores the story behind its name. What catches your attention about this place?", "Madagascar": "Your class explores Tenrec. What catches your attention about this place?", "Mauritius": "Your class explores Seven Coloured Earths. What catches your attention about this place?", "South Africa": "Your class explores its different capital cities. What catches your attention about this place?", "Lesotho": "Your class explores Matekane Airstrip. What catches your attention about this place?", "Eswatini": "Your class explores Ngwenya Glass. What catches your attention about this place?", "Malawi": "Your class explores Lake Malawi. What catches your attention about this place?"});
